[package]
name = "injector"
version = "0.1.0"
edition = "2024"

[lib]
path = "src/lib.rs"

[dependencies]
clipboard = { path = "../clipboard" }
cocoa = { workspace = true }
core-graphics = "0.24"
arboard = { workspace = true }
tokio = { workspace = true, features = ["rt", "time"] }
anyhow = { workspace = true }
log = { workspace = true }
